name: Label PRs

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  label_prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Label PRs
        uses: actions/github-script@v7
        with:
          script: |
            const label_pr = require('./.github/scripts/label_pr.js')
            await label_pr({github, context})

