name: Label PRs test

on:
  pull_request:
    types: [opened]

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const prBody = context.payload.pull_request.body;
            const repo = context.repo;

            const issueNumberMatch = prBody.match(/(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) #(\d+)/i);
            if (!issueNumberMatch) {
              console.log("No issue reference found in PR description.");
              return;
            }

            const issueNumber = issueNumberMatch[1];
            const issue = await github.rest.issues.get({
              ...repo,
              issue_number: issueNumber,
            });

            const issueLabels = issue.data.labels.map(label => label.name);
            if (issueLabels.length > 0) {
              await github.rest.issues.setLabels({
                ...repo,
                issue_number: prNumber,
                labels: issueLabels,
              });
            }